# Project information
site_name: Floflis Docs
site_description: 'Official documentation for Floflis'
site_author: 'Daniella Mesquita'
site_url: 'https://floflis.github.io/docs'

# Repository
repo_name: 'Floflis/docs-source'
repo_url: 'https://github.com/Floflis/docs-source'

# Copyright
copyright: '(c) 2019-2023 Floflis Platform'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'

# Customization
extra:
  manifest: 'manifest.webmanifest'
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/floflis'
      name: 'Github'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/FloflisOS'
      name: 'Twitter'
    - icon: fontawesome/brands/youtube
      link: 'https://www.youtube.com/channel/UCqboYZIRwremiHzqcvBdlYg'
      name: 'Youtube'
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/kcnYFqp'
      name: 'Discord'
    - icon: fontawesome/brands/gitlab
      link: 'https://gitlab.com/floflis'
      name: 'Gitlab'
    - icon: fontawesome/solid/globe-europe
      link: 'https://floflis.github.io'
      name: 'Site'
    - icon: fontawesome/solid/tachometer-alt
      link: 'http://status.floflis.com'
      name: 'Status of Floflis'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

# Navigation
nav:
    - Welcome to Floflis: index.md
    - Floflis Layers: layers.md
    - Installing: installing.md
    - Updating: updating.md
    - Floflis Central app (draft, outdated): flofliscentral.md
    - Tree folder (WIP): treefolder.md
    - Floflis files (draft): floflisfiles.md
    - Developers (draft): dev.md
    - Frequently Asked Questions: faq.md
    - Return to site: https://floflis.github.io/
